### ISSUE TITLE
Just leaving a footprint :-) 

### ISSUE THREAD

**Issue by engdan77** [zerowon01/servstat#1]
Nice work @zerowon01  (didn't mean to add it as an "issue"), wasn't sure if/how to connect through GitHub so just leaving this footprint to be able to follow this crumble later if I lost you .. (guess your alias confused me) . .. we should collaborate on "project" project sometime in the future .. if you need anything useful from personal projects you'd find those here https://github.com/engdan77 .. till next time .. :-)

**Comment by greigbl** [comment]
A good issue; I like it.
